import { User, Evento, Aviso } from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    nome: "Pastor João Silva",
    email: "pastor@ramo.church",
    telefone: "(11) 99999-0001",
    role: "pastor",
    ministerios: ["Ensino", "Louvor"],
    dataIngresso: "2018-03-10",
    ativo: true,
  },
  {
    id: "2",
    nome: "Admin Maria Costa",
    email: "admin@ramo.church",
    telefone: "(11) 99999-0002",
    role: "admin",
    ministerios: ["Mídias"],
    dataIngresso: "2019-06-15",
    ativo: true,
  },
  {
    id: "3",
    nome: "Pedro Alves",
    email: "pedro@ramo.church",
    telefone: "(11) 99999-0003",
    role: "lider",
    ministerios: ["Jovens", "Louvor"],
    dataIngresso: "2020-01-20",
    ativo: true,
  },
  {
    id: "4",
    nome: "Ana Rodrigues",
    email: "ana@ramo.church",
    role: "voluntario",
    ministerios: ["Infantil", "Cantina"],
    dataIngresso: "2021-07-05",
    ativo: true,
  },
  {
    id: "5",
    nome: "Lucas Ferreira",
    email: "lucas@ramo.church",
    role: "membro",
    ministerios: ["Ação Social"],
    dataIngresso: "2022-02-14",
    ativo: true,
  },
];

export const mockEventos: Evento[] = [
  {
    id: "e1",
    titulo: "Culto de Celebração",
    descricao: "Culto dominical com louvor e pregação.",
    data: "2026-04-20",
    horario: "10:00",
    local: "Templo Principal",
    publico: true,
    ministerio: "Louvor",
  },
  {
    id: "e2",
    titulo: "Reunião de Jovens",
    descricao: "Encontro semanal da juventude.",
    data: "2026-04-18",
    horario: "19:30",
    local: "Sala 3",
    publico: false,
    ministerio: "Jovens",
  },
  {
    id: "e3",
    titulo: "Ação Social no Bairro",
    descricao: "Distribuição de alimentos e roupas.",
    data: "2026-04-27",
    horario: "09:00",
    local: "Praça Central",
    publico: true,
    ministerio: "Ação Social",
  },
  {
    id: "e4",
    titulo: "Treinamento de Líderes",
    descricao: "Capacitação para líderes de ministério.",
    data: "2026-05-03",
    horario: "14:00",
    local: "Sala de Reuniões",
    publico: false,
    ministerio: "Ensino",
  },
];

export const mockAvisos: Aviso[] = [
  {
    id: "a1",
    titulo: "Reunião Geral de Membros",
    conteudo: "Haverá uma reunião geral no próximo sábado às 16h.",
    criadoEm: "2026-04-14",
    destinatarios: "todos",
  },
  {
    id: "a2",
    titulo: "Ensaio do Louvor",
    conteudo: "O ensaio de louvor foi remarcado para quinta-feira às 19h.",
    criadoEm: "2026-04-13",
    destinatarios: ["lider", "voluntario"],
    ministerio: "Louvor",
  },
  {
    id: "a3",
    titulo: "Relatório Financeiro",
    conteudo: "O relatório do mês de março está disponível para revisão.",
    criadoEm: "2026-04-10",
    destinatarios: ["admin", "pastor"],
  },
];
